### PR TITLE
fix: cache account type for multi-thread access

### LINKED ISSUE #758: Regression in External Plugin Notifier
Just noticed that my dink notifications in watchdog weren't working, traced the issue to this PR (I think). Looks like this change now requires you to be on the client thread since it calls `getVarbitValue`. I can put my event bus post on the client thread, but I would imagine you probably would just want to do that yourself in your code.

_Originally posted by @adamk33n3r in https://github.com/pajlads/DinkPlugin/issues/701#issuecomment-2964719911_

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #758

### CODE REVIEW

File: src/main/java/dinkplugin/util/AccountTypeTracker.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        var accountType = AccountType.get(client.getVarbitValue(VarbitID.IRONMAN));
+        if (player == null || player.getName() == null || accountType == null) {
+            this.state = null;
+            return;
+        } else if (config.nameFilterMode() != FilterMode.ALLOW && config.deniedAccountTypes().contains(accountType)) {
+            this.state = false;
+        } else {
+            this.state = settingsManager.isNamePermitted(player.getName());
+        }
+        log.debug("Initialized account tracker for {} {}: {}", accountType, player.getName(), state);
```
Comment (pajlada) [inline src/main/java/dinkplugin/util/AccountTypeTracker.java:28]: to make use of `this.state` consistent within the file
```suggestion
        log.debug("Initialized account tracker for {} {}: {}", accountType, player.getName(), this.state);
```

File: src/main/java/dinkplugin/util/WorldTypeTracker.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+public class WorldTypeTracker extends BooleanStateTracker {
+
+    @Override
+    protected void populateState() {
+        Set<WorldType> world = client.getWorldType();
+        if (config.seasonalPolicy() == SeasonalPolicy.REJECT && world.contains(WorldType.SEASONAL)) {
+            this.state = false;
+        } else {
+            this.state = !WorldUtils.isIgnoredWorld(world);
+        }
```
Comment (pajlada) [inline src/main/java/dinkplugin/util/WorldTypeTracker.java:21]: imo this is more readable, so I'd prefer this. not a hill I'll die on though

```suggestion
        } else if (WorldUtils.isIgnoredWorld(world) {
            this.state = false;
        } else {
            this.state = true;
        }
```

**Review by pajlada — APPROVED** [review]
small nits, otherwise looks good & seems to work as expected in-game
