### PR TITLE
fix: prevent old state from appearing in later notifs

### LINKED ISSUE #62: Clue Scrolls: Master Clue scrolls might not post correctly
**Dink version:** 1.0.3
**RuneLite version:** 1.9.3

On both Universal and Dink, the master clue scroll reward i got didn't post on my Discord webhook. However after completing a beginner clue scroll, the reward of the master clue scroll reward got posted as a beginner clue.

Master Clue merged with Beginner clue

I also use other Discord webhook plugins like Rare Drop Notifier since i post to different webhook notifications to different text channels (clues for clue channel, levels for level channel, loot for loot channel etc.), I'm not sure if this is a webhook issue or a plugin issue. Since i also got this issue on Universal Discord, i think it could lie in the plugin itself.

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #62

Intuition: clue and slayer notifiers require two event calls to gather all of the data to create the notification. It is possible for only one of these events to be accurately parsed (e.g., transient network issue or too strict regex). As a result, when the next event occurs, it will notify using partially old data. To avoid this, if the notifier is in a partially-parsed state for 2+ ticks, we clear the data (as it does not appear that the complementary event will occur). 

This can be seen as a hotfix while we investigate why the complementary event sometimes is not successfully parsed (or possibly doesn't arrive)

Note: we also simplify the event handling based on the order in which the two events are supposed to be received

### CODE REVIEW

File: src/main/java/dinkplugin/notifiers/ClueNotifier.java [hunk 1]
```diff
@@ -84,6 +85,16 @@ public void onWidgetLoaded(WidgetLoaded event) {
         }
     }
 
+    public void onTick() {
+        // Track how many ticks occur where we only have partial clue data
+        if (clueCount == null != clueItems.isEmpty()) // XOR
+            badTicks++;
+
+        // Clear data if over 8 ticks pass with only partial parsing
+        if (badTicks > 8)
```
Comment (iProdigy) [inline src/main/java/dinkplugin/notifiers/ClueNotifier.java:94]: Since some people like to open many caskets in succession, should this be less than 8? less than 4? (i'm not sure what's the max possible delay btwn widget & chat message)

**Review by pajlada — APPROVED** [review]
Code looks good to me, with something like this it's always best to do a little testing :pinching_hand: before merging in

**Comment by pajlada** [comment]
Tested clue scrolls with this and it works as expected
