### PR TITLE
fix(death): ignore more safe areas

### LINKED ISSUE #188: Add option to toggle off LMS death spam
Mm2PL has died...
Mm2PL has died...
Mm2PL has died...
Mm2PL has died...
Mm2PL has died...
Mm2PL has died...

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #188 (but not toggleable)

https://oldschool.runescape.wiki/w/Minigames#Safe

### CODE REVIEW

File: src/main/java/dinkplugin/util/WorldUtils.java [hunk 1]
```diff
@@ -18,17 +17,21 @@ public class WorldUtils {
...
-    @VisibleForTesting
-    public final int CASTLE_WARS_COUNTDOWN = 380;
-    @Varbit
-    private final int CASTLE_WARS_X_OFFSET = 156;
-    @Varbit
-    private final int CASTLE_WARS_Y_OFFSET = 157;
+    private final Set<Integer> SOUL_REGIONS = ImmutableSet.of(8493, 8748, 8749, 9005);
+    private final Set<Integer> TZHAAR_REGIONS = ImmutableSet.of(9551, 9552);
+    private final int BURTHORPE_REGION = 8781;
+    private final int INFERNO_REGION = 9043;
```
Comment (Felanbird) [inline src/main/java/dinkplugin/util/WorldUtils.java:30]: I think Inferno and Jad should probably be removed from this, while they do fit the blanket statement of Safe, as you don't lose anything, people would like to know if you died to jad or inferno, since you actually lose out on something.

Comment (iProdigy) [reply src/main/java/dinkplugin/util/WorldUtils.java:29]: Fixed in https://github.com/pajlads/DinkPlugin/pull/194/commits/941eec62ffc636dcca62df60d7a96c6f5bb65071

File: src/main/java/dinkplugin/notifiers/DeathNotifier.java [hunk 2]
```diff
@@ -276,4 +277,17 @@ private static List<SerializedItemStack> getStacks(ItemManager itemManager, List
...
+     * @param client {@link Client}
+     * @return whether the player is not in a safe area (excluding inferno and fight cave)
+     */
+    private static boolean isDangerous(Client client) {
+        if (!WorldUtils.isSafeArea(client))
+            return true; // normally dangerous
+
+        // inferno and fight cave are technically safe, but we want death notification regardless
+        int regionId = client.getLocalPlayer().getWorldLocation().getRegionID();
+        return WorldUtils.isInferno(regionId) || WorldUtils.isTzHaarFightCave(regionId);
```
Comment (iProdigy) [inline src/main/java/dinkplugin/notifiers/DeathNotifier.java:290]: This is consistent with maintaining current behavior - in a future version we could make these config toggles if desired

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,7 +4,7 @@
 - Minor: Include number of quest completions and quest points in quest notifications. (#178)
 - Minor: Collapse all notifier configuration sections by default. (#176)
 - Minor: Include number of completed entries in collection log notification. (#174, #181)
-- Bugfix: Include PKer from Last Man Standing minigame in death notifications. (#187)
+- Bugfix: Avoid death notifications for more safe activities. (#194)
```
Comment (pajlada) [inline CHANGELOG.md:7]: Can we change this to a Minor changelog entry, and list which areas have changed?
CC @Felanbird for feedback on this

**Review by pajlada — CHANGES_REQUESTED** [review]
I would also like to propose including details about ignored deaths in the readme under the Death header, something along the lines of:

"Deaths in areas that are considered safe deaths will not fire off notifications. These are the zones we consider safe: blah blah, with the exception of blah blah and blah for group hardcore ironmen"

File: CHANGELOG.md (hunk 3 above)
Comment (Felanbird) [reply CHANGELOG.md:7]: ya sure

**Review by pajlada — APPROVED** [review]
