### PR TITLE
fix: match non-latin slayer tasks

### LINKED ISSUE #2: Slayer regex doesn't handle names with non-latin letters
The regex can be found here: https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/universalDiscord/UniversalDiscordPlugin.java#L67

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #2

### CODE REVIEW

File: src/main/java/universalDiscord/UniversalDiscordPlugin.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ public class UniversalDiscordPlugin extends Plugin {
     private final ClueNotifier clueNotifier = new ClueNotifier(this);
 
     private static final Pattern CLUE_SCROLL_REGEX = Pattern.compile("You have completed (?<scrollCount>\\d+) (?<scrollType>\\w+) Treasure Trails\\.");
-    private static final Pattern SLAYER_TASK_REGEX = Pattern.compile("You have completed your task! You killed (?<task>[\\d,]+ [\\w,]+)\\..*");
+    private static final Pattern SLAYER_TASK_REGEX = Pattern.compile("You have completed your task! You killed (?<task>[\\d,]+ [\\w,']+)\\..*", Pattern.UNICODE_CHARACTER_CLASS);
```
Comment (iProdigy) [inline src/main/java/universalDiscord/UniversalDiscordPlugin.java:67]:
```suggestion
    private static final Pattern SLAYER_TASK_REGEX = Pattern.compile("You have completed your task! You killed (?<task>[\\d,]+ [^\\.]+)\\..*");
```

Comment (pajlada) [reply src/main/java/universalDiscord/UniversalDiscordPlugin.java]: Suggestion applied in a commit further down
