### PR TITLE
fix: treat gauntlet deaths as safe unless hardcore iron

### LINKED ISSUE #326: [Bug] CG deaths are considered dangerous for non-hardcore accounts
To test, die in CG to hunllef immediately after entering with "ignore safe deaths" toggled OFF, and set min lost value to 4. The death will not track. 

Set min lost value to 3. Immediately die to hunllef, and it will track.

(These numbers are based off current GE pestle + mortar price, which is 3 gp as of 10/3/2023)

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #326

### CODE REVIEW

File: src/main/java/dinkplugin/util/WorldUtils.java [hunk 1]
```diff
@@ -28,6 +28,7 @@ public class WorldUtils {
     private final Set<Integer> POH_REGIONS = ImmutableSet.of(7257, 7513, 7514, 7769, 7770, 8025, 8026);
     private final Set<Integer> SOUL_REGIONS = ImmutableSet.of(8493, 8748, 8749, 9005);
     private final Set<Integer> TOA_REGIONS = ImmutableSet.of(14160, 14162, 14164, 14674, 14676, 15184, 15186, 15188, 15696, 15698, 15700);
+    private final Set<Integer> GAUNTLET_REGIONS = ImmutableSet.of(7512, 7768, 12127); // includes CG
```
Comment (Felanbird) [inline src/main/java/dinkplugin/util/WorldUtils.java:31]: dont forget to alphabet me

**Review by Felanbird — APPROVED** [review]
works
image
image

**Review by pajlada — APPROVED** [review]
