### PR TITLE
fix: recognize diary resurrections as safe deaths

### LINKED ISSUE #548: Handle zulrah/fight caves resurrections
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

For completing Elite Western Provinces and Elite Karamja diaries you gain an ability to get resurrected at Zulrah fight and Fight Caves, respectively - once per day.
Both of those result in dink sending a death notification being fired, while, in fact, you do not die. Your hp & prayer get fully healed and a message - it is indicated with a "healing" hitsplat on your character, a sound effect as well as a chat message being sent into 'Game' chat. In the case of Fight Caves, the monsters also get de-aggro'd for a very brief moment of time.

I suggest that this should be handled to either fully be ignored by the death notifier or treated as a safe death (so don't be sent out if safe deaths are ignored). Alternatively, consider making this another entry in the 'Safe Exceptions' section.

The example of such event triggering at Zulrah:
in-game chat message informing player about zulrah resurrection
`The blerssing bestowed upon you for completing the Western elite diary empowers you to continue. Carry on the fight!`

The example of such event triggering in the Fight Caves:
in-game chat message informing player about Fight Caves resurrection
`The blerssing bestowed upon you for completing the Karamja elite diary empowers you to continue. Carry on the fight!`

### Screenshots

_No response_

### Runelite Logs

N/A

### Runelite Version

1.10.37.1

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #548

https://www.youtube.com/watch?v=UmSkDAStKeE

### CODE REVIEW

File: src/main/java/dinkplugin/notifiers/DeathNotifier.java [hunk 1]
```diff
@@ -127,16 +139,26 @@ protected String getWebhookUrl() {
...
         if ("deathIgnoredRegions".equals(key)) {
-            setIgnoredRegions(value);
+            clientThread.invoke(() -> setIgnoredRegions(value));
+        }
+    }
+
+    public void onVarbit(VarbitChanged event) {
+        if (event.getValue() != 1) return;
+        if (event.getVarbitId() == KARAMJA_RESURRECTION_USED || event.getVarbitId() == WESTERN_RESURRECTION_USED) {
+            this.resurrectedAt = Instant.now();
```
Comment (iProdigy) [inline src/main/java/dinkplugin/notifiers/DeathNotifier.java:161]: if this approach works, we could use game message instead of undocumented varbits if desired

Comment (Felanbird) [reply src/main/java/dinkplugin/notifiers/DeathNotifier.java:161]: >undocumented varbits 

wrong repo

**Review by Felanbird — APPROVED** [review]
works

**Review by pajlada — APPROVED** [review]
Looks sane to me
