### PR TITLE
fix: import death safe exceptions

### LINKED ISSUE #405: Import Command Does Not Update Safe Death Exceptions
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

When using the ::dinkimport all command, the "Safe Exceptions" section of Deaths does not update. Here is the deathSafeExceptions obj from our import file - "deathSafeExceptions":["JAD_CHALLENGES","INFERNO","TOB","FIGHT_CAVE","TOA","COX"] if you'd like the whole config file please PM me.

### Screenshots

death_settings
dink_import_msg

### Runelite Logs

[launcher.log](https://github.com/pajlads/DinkPlugin/files/13922395/launcher.log)
[client.log](https://github.com/pajlads/DinkPlugin/files/13922397/client.log)

### Runelite Version

1.10.19

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #405

### CODE REVIEW

File: src/main/java/dinkplugin/util/ConfigUtil.java [hunk 1]
```diff
@@ -98,6 +101,17 @@ public Object convertTypeFromJson(@NotNull Type type, @NotNull Object in) {
             }
         }
 
+        if (in instanceof Collection && type instanceof ParameterizedType) {
+            Type rawType = ((ParameterizedType) type).getRawType();
+            if (rawType instanceof Class && Collection.class.isAssignableFrom((Class<?>) rawType)) {
+                try {
+                    return gson.fromJson(gson.toJson(in), type); // TODO: make more efficient
```
Comment (iProdigy) [inline src/main/java/dinkplugin/util/ConfigUtil.java:108]: optimizing this is probably not worth

```diff
--- a/src/main/java/dinkplugin/util/ConfigUtil.java	(revision 7e708a656c522fe9f2dc74c83899d56cae416f8c)
+++ b/src/main/java/dinkplugin/util/ConfigUtil.java	(revision 08d37fe24e4204ed5f10ec297c4b774b6f6aeb09)
@@ -2,6 +2,7 @@
 
 import com.google.gson.Gson;
 import lombok.experimental.UtilityClass;
+import lombok.extern.slf4j.Slf4j;
 import net.runelite.api.Client;
 import net.runelite.api.widgets.ComponentID;
 import net.runelite.api.widgets.Widget;
@@ -16,9 +17,12 @@
 import java.time.Duration;
 import java.time.Instant;
 import java.util.Collection;
+import java.util.EnumSet;
+import java.util.Set;
 import java.util.regex.Pattern;
 import java.util.stream.Stream;
 
+@Slf4j
 @UtilityClass
 public class ConfigUtil {
 
@@ -102,17 +106,35 @@
         }
 
         if (in instanceof Collection && type instanceof ParameterizedType) {
-            Type rawType = ((ParameterizedType) type).getRawType();
+            ParameterizedType pType = (ParameterizedType) type;
+            Type rawType = pType.getRawType();
             if (rawType instanceof Class && Collection.class.isAssignableFrom((Class<?>) rawType)) {
+                Type[] args = pType.getActualTypeArguments();
+                if (args != null && args.length == 1) {
+                    Type eType = args[0];
+                    if (eType instanceof Class && Enum.class.isAssignableFrom((Class<?>) eType)) {
+                        //noinspection unchecked,rawtypes
+                        return convert((Class<? extends Enum>) eType, (Collection<?>) in);
+                    }
+                }
+            }
+        }
+
+        return null;
+    }
+
+    private <E extends Enum<E>> Set<E> convert(Class<E> enumClass, Iterable<?> values) {
+        Set<E> set = EnumSet.noneOf(enumClass);
+        for (Object value : values) {
+            if (value instanceof String) {
                 try {
-                    return gson.fromJson(gson.toJson(in), type); // TODO: make more efficient
-                } catch (Exception e) {
-                    return null;
+                    set.add(Enum.valueOf(enumClass, (String) value));
+                } catch (IllegalArgumentException e) {
+                    log.debug("Encountered unknown enum value for {}: {}", enumClass.getSimpleName(), value, e);
                 }
             }
         }
-
-        return null;
+        return set;
     }
 
     public boolean isSettingsOpen(@NotNull Client client) {
```

**Review by Felanbird — APPROVED** [review]

**Review by pajlada — APPROVED** [review]
Code looks fine to me, I haven't tested it
