### PR TITLE
fix(quest): ignore partial completions

### LINKED ISSUE #204: Hazeel cult parital completion triggers a quest event
When siding with Ceril on the quest 'Hazeel Cult' the partial completion mid way through the quest triggers a quest notification.

`Extra: { questName: 'Hazeel Cult partial completion' }`

Easy enough to filter out server side, but may be worth filtering client side for others.

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #204

### CODE REVIEW

File: src/main/java/dinkplugin/util/QuestUtils.java [hunk 1]
```diff
@@ -46,21 +53,20 @@ public class QuestUtils {
...
-        final Matcher questMatch1 = QUEST_PATTERN_1.matcher(text);
-        // "'One Small Favour' completed!"
-        final Matcher questMatch2 = QUEST_PATTERN_2.matcher(text);
-        final Matcher questMatchFinal = questMatch1.matches() ? questMatch1 : questMatch2;
-        if (!questMatchFinal.matches()) {
-            return "Unable to find quest name!";
+        Matcher matcher = getMatcher(text);
+        if (matcher == null) {
+            log.warn("Unable to match quest: {}", text);
+            return null;
```
Comment (iProdigy) [inline src/main/java/dinkplugin/util/QuestUtils.java:61]: We could return `"Unknown quest"` or `text` here if we want a notification fired for quest completions that don't match the regexps... thoughts?

Comment (pajlada) [reply src/main/java/dinkplugin/util/QuestUtils.java:61]: `null` seems fine here imo until we feel like we have a use for the distinction

**Review by pajlada — APPROVED** [review]
Change is small enough that I'm comfortable with this without too much testing, I did Cook's Assistant and it works as expected :+1: 
image
