### PR TITLE
fix: respect min difficulty config for diary notifier

### LINKED ISSUE #381: Achivement diary min value is ignored
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

The `Achievement Diary -> Min Difficulty` value is set to "Elite" as I only want to notify on Elite diary completion. However, this setting isn't being respected and instead all Diary tier notifications are being sent. 

I believe the following bit of code is responsible for checking this: https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/DiaryNotifier.java#L208-L210

I don't see anything wrong with the code at first glance, unless the value isn't persisted to the config perhaps?

### Screenshots

_No response_

### Runelite Logs

Nothing substantial in the logs except a massive repetition of the following: 
```
[Client] WARN  dinkplugin.SettingsManager - Pet Notifier cannot reliably identify pet names unless you enable the game setting: Untradeable loot notifications
```

### Runelite Version

1.10.17.1

### PR DESCRIPTION
**Pull request by redrails**
Closes #381 

Couple of extra notes:
- The provided gradle wrapper doesn't build for me unless I change `rootProject.name = "DinkPlugin"` i.e. camel case, I've not included that as apart of the PR as it's not relevant but just wondering if this is a "me" issue.
- Although just semantics, `checkDifficulty` maybe not the best name for this method - perhaps `passesDifficulty` or similar maybe better... Not important for now though 🙂

### CODE REVIEW

File: src/main/java/dinkplugin/notifiers/DiaryNotifier.java [hunk 1]
```diff
@@ -107,6 +107,11 @@ public void onMessageBox(String message) {
                 return;
             }
 
+            if (!checkDifficulty(difficulty)) {
```
Comment (iProdigy) [inline src/main/java/dinkplugin/notifiers/DiaryNotifier.java:110]: Could you move this check just before the `invokeLater` call so `diaryCompletionById` is updated even if a notification is not fired?

**Review by iProdigy — COMMENTED** [review]
Thanks for the contribution & adding a mock test!

File: src/main/java/dinkplugin/notifiers/DiaryNotifier.java (hunk 1 above)
Comment (redrails) [reply src/main/java/dinkplugin/notifiers/DiaryNotifier.java]: All done, what's the point of this map? Wouldn't it be discarded on a new invocation of this notifier?

Comment (iProdigy) [reply src/main/java/dinkplugin/notifiers/DiaryNotifier.java]: thanks! `diaryCompletionById` is useful to avoid duplicate notifications (not relevant in this case), and to report the total number of diaries that have been completed (so a low-tier completion is still relevant for later high-tier completions): https://github.com/pajlads/DinkPlugin/blob/ad4d733d0cb45345fbdcf132b68b99f68fe292b8/src/main/java/dinkplugin/notifiers/DiaryNotifier.java#L189

File: src/main/java/dinkplugin/notifiers/DiaryNotifier.java [hunk 2]
```diff
@@ -119,6 +119,10 @@ public void onMessageBox(String message) {
                 } else {
                     diaryCompletionById.put(varbitId, 2);
                 }
+                if (!checkDifficulty(difficulty)) {
+                    log.warn("Ignoring diary notification as difficulty threshold isn't met ({} <= {})", difficulty, config.minDiaryDifficulty().name());
```
[the remark this answers is not in the document]
Comment (redrails) [reply src/main/java/dinkplugin/notifiers/DiaryNotifier.java]: Removed the log entirely so that the code remains clean, don't see a reason to have debug here...

**Review by pajlada — APPROVED** [review]
Works as expected, thank you for your contribution!

**Review by Felanbird — APPROVED** [review]
I tested it the other day as well and it worked, tyvm :+1:

idk when this change will make it to you tho, currently we have a PR nobody remembered to merge with a change related to native runelite changes, so sometime after that gets merged ig
